### ISSUE TITLE
print_range の定義がありません。

### ISSUE THREAD

**Issue by yanzm** [yomichi/JuliaBook-Samples#7]
P89 で 「print_range は以前定義した関数です。」とありますが、本文中に print_range の定義はされていないと思います。

**Comment by yomichi** [comment]
ありがとうございます、いろいろ改訂したときに忘れ去っていた ＆ REPL を初期化するのを忘れて気づかなかったようです。
もともとイテレータの中身を（紙面の節約のために）一行で表示したかったのですが、 `join` 関数を使えばだいたい似たようなことができることに思い至りました。
